<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License BY-NC-ND.
 * NonCommercial — You may not use the material for commercial purposes.
 * NoDerivatives — If you remix, transform, or build upon the material,
 * you may not distribute the modified material.
 * See the full license at http://creativecommons.org/licenses/by-nc-nd/4.0/
 *
 * See http://mventory.com/legal/licensing/ for other licensing options.
 *
 * @package MVentory/UIVideoTab
 * @copyright Copyright (c) 2015 mVentory Ltd. (http://mventory.com)
 * @license http://creativecommons.org/licenses/by-nc-nd/4.0/
 */

/**
 * Product video template
 *
 * @package MVentory/UIVideoTab
 * @author Anatoly A. Kazantsev <anatoly@mventory.com>
 */

?>

<h2><?php echo $this->getTitle() ?></h2>
<div class="ui-product-video">
  <iframe src="https://www.youtube.com/embed/<?php echo $this->_getVideo() ?>" frameborder="0" allowfullscreen></iframe>
</div>
